---
- hosts: app
  become: yes

  roles:
    - common
    - appserver

# roles/appserver/tasks/main.yml
---
- name: Install Python dependencies
  yum:
    name: 
      - python3
      - python3-pip
    state: present

- name: Install application dependencies
  pip:
    name: 
      - flask
      - gunicorn

- name: Deploy application code
  git:
    repo: 'https://github.com/your-repo/app.git'
    dest: /opt/app

- name: Configure Gunicorn to run as a service
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
  notify: Restart Gunicorn

# roles/appserver/handlers/main.yml
---
- name: Restart Gunicorn
  systemd:
    name: gunicorn
    state: restarted

# roles/appserver/templates/gunicorn.service.j2
---
[Unit]
Description=Gunicorn instance to serve the app
After=network.target

[Service]
User=ec2-user
Group=nginx
WorkingDirectory=/opt/app
ExecStart=/usr/local/bin/gunicorn --workers 3 --bind 0.0.0.0:8000 wsgi:app

[Install]
WantedBy=multi-user.target
