---
- hosts: db
  become: yes

  roles:
    - common
    - dbserver

# roles/dbserver/tasks/main.yml
---
- name: Install MySQL
  yum:
    name: mysql-server
    state: present

- name: Start MySQL
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Secure MySQL installation
  mysql_secure_installation:

- name: Create application database and user
  mysql_db:
    name: app_db
  mysql_user:
    name: app_user
    password: "secure_password"
    priv: 'app_db.*:ALL'
