---

-name: Install and configure nginx
hosts: webserver
become: root

tasks: 
-name: Install nginx
  apt: 
   name: ngnix
   state: present

-name: start nginx
sevice: 
      name: nginx
      state: started
      enabled: true 
